import pytest
from src_0065 import task_func

def test_task_func():
    data = [
        ['A', 'B', 'C'],
        ['A', 'B', 'C'],
        ['A', 'B', 'D'],
        ['A', 'B', 'D'],
        ['A', 'C', 'D'],
        ['A', 'C', 'D'],
        ['B', 'C', 'D'],
        ['B', 'C', 'D'],
        ['B', 'C', 'E'],
        ['B', 'C', 'E'],
        ['B', 'D', 'E'],
        ['B', 'D', 'E'],
        ['C', 'D', 'E'],
        ['C', 'D', 'E'],
        ['C', 'D', 'F'],
        ['C', 'D', 'F'],
        ['D', 'E', 'F'],
        ['D', 'E', 'F'],
        ['E', 'F', 'G'],
        ['E', 'F', 'G'],
        ['F', 'G', 'H'],
        ['F', 'G', 'H'],
        ['G', 'H', 'I'],
        ['G', 'H', 'I'],
        ['H', 'I', 'J'],
        ['H', 'I', 'J'],
        ['I', 'J', 'K'],
        ['I', 'J', 'K'],
        ['J', 'K', 'L'],
        ['J', 'K', 'L'],
        ['K', 'L', 'M'],
        ['K', 'L', 'M'],
        ['L', 'M', 'N'],
        ['L', 'M', 'N'],
        ['M', 'N', 'O'],
        ['M', 'N', 'O'],
        ['N', 'O', 'P'],
        ['N', 'O', 'P'],
        ['O', 'P', 'Q'],
        ['O', 'P', 'Q'],
        ['P', 'Q', 'R'],
        ['P', 'Q', 'R'],
        ['Q', 'R', 'S'],
        ['Q', 'R', 'S'],
        ['R', 'S', 'T'],
        ['R', 'S', 'T'],
        ['S', 'T', 'U'],
        ['S', 'T', 'U'],
        ['T', 'U', 'V'],
        ['T', 'U', 'V'],
        ['U', 'V', 'W'],
        ['U', 'V', 'W'],
        ['V', 'W', 'X'],
        ['V', 'W', 'X'],
        ['W', 'X', 'Y'],
        ['W', 'X', 'Y'],
        ['X', 'Y', 'Z'],
        ['X', 'Y', 'Z'],
        ['Y', 'Z', 'A'],
        ['Y', 'Z', 'A'],
        ['Z', 'A', 'B'],
        ['Z', 'A', 'B'],
    ]
    expected_analyzed_df = pd.DataFrame(
        {
            'col1': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
            'col2': ['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
            'col3': ['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
        }
    )
    expected_ax = sns.heatmap(expected_analyzed_df, annot=True)
    analyzed_df, ax = task_func(data)
    assert analyzed_df.equals(expected_analyzed_df)
    assert ax == expected_ax